# Generated by Django 5.0.4 on 2024-06-20 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadFiscalizacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anyo', models.IntegerField(blank=True, null=True)),
                ('trimestre', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'actividad_fiscalizacion',
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='archivos/')),
                ('nombre', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'archivo',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'clasificacion',
            },
        ),
        migrations.CreateModel(
            name='Enfoque',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'enfoque',
            },
        ),
        migrations.CreateModel(
            name='EstatusObservacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'estatus_observacion',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'materia',
            },
        ),
        migrations.CreateModel(
            name='Oic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'oic',
            },
        ),
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'programacion',
            },
        ),
        migrations.CreateModel(
            name='Temporalidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'temporalidad',
            },
        ),
        migrations.CreateModel(
            name='TipoIntervencion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'tipo_intervencion',
            },
        ),
        migrations.CreateModel(
            name='TipoMinuta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'tipo_minuta',
            },
        ),
        migrations.CreateModel(
            name='TipoRevision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'tipo_revision',
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('denominacion', models.CharField(blank=True, max_length=2000, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('objetivo', models.CharField(blank=True, max_length=2000, null=True)),
                ('oportunidad', models.CharField(blank=True, max_length=2000, null=True)),
                ('alcance', models.CharField(blank=True, max_length=2000, null=True)),
                ('ejercicio', models.CharField(blank=True, max_length=4, null=True)),
                ('unidad', models.CharField(blank=True, max_length=500, null=True)),
                ('id_actividad_fiscalizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.actividadfiscalizacion')),
                ('id_enfoque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.enfoque')),
                ('id_materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.materia')),
                ('id_programacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.programacion')),
                ('id_temporalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.temporalidad')),
            ],
            options={
                'db_table': 'auditoria',
            },
        ),
        migrations.CreateModel(
            name='Cedula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_actividad_fiscalizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.actividadfiscalizacion')),
            ],
            options={
                'db_table': 'cedula',
            },
        ),
        migrations.CreateModel(
            name='ConceptoCedula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('celda', models.CharField(max_length=3)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('comentario', models.CharField(blank=True, max_length=500, null=True)),
                ('id_cedula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.cedula')),
            ],
            options={
                'db_table': 'concepto_cedula',
            },
        ),
        migrations.CreateModel(
            name='ControlInterno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unidad', models.CharField(blank=True, max_length=500, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('rubro', models.CharField(blank=True, max_length=500, null=True)),
                ('ejercicio', models.CharField(blank=True, max_length=4, null=True)),
                ('id_actividad_fiscalizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.actividadfiscalizacion')),
                ('id_tipo_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.tiporevision')),
            ],
            options={
                'db_table': 'control_interno',
            },
        ),
        migrations.CreateModel(
            name='Intervencion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unidad', models.CharField(blank=True, max_length=500, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('denominacion', models.CharField(blank=True, max_length=500, null=True)),
                ('rubro', models.CharField(blank=True, max_length=500, null=True)),
                ('ejercicio', models.CharField(blank=True, max_length=4, null=True)),
                ('id_actividad_fiscalizacion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.actividadfiscalizacion')),
                ('id_tipo_intervencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.tipointervencion')),
            ],
            options={
                'db_table': 'intervencion',
            },
        ),
        migrations.CreateModel(
            name='Minuta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
                ('id_actividad_fiscalizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.actividadfiscalizacion')),
                ('id_archivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.archivo')),
                ('id_tipo_minuta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.tipominuta')),
            ],
            options={
                'db_table': 'minuta',
            },
        ),
        migrations.CreateModel(
            name='ConceptoMinuta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=3)),
                ('estatus', models.IntegerField(blank=True, null=True)),
                ('comentario', models.CharField(blank=True, max_length=500, null=True)),
                ('id_minuta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.minuta')),
            ],
            options={
                'db_table': 'concepto_minuta',
            },
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(blank=True, max_length=2, null=True)),
                ('denominacion', models.CharField(blank=True, max_length=500, null=True)),
                ('monto_observado', models.FloatField(blank=True, null=True)),
                ('monto_aclarado', models.FloatField(blank=True, null=True)),
                ('monto_recuperado', models.FloatField(blank=True, null=True)),
                ('fecha_incurrencia', models.DateField(blank=True, null=True)),
                ('fecha_compromiso', models.DateField(blank=True, null=True)),
                ('clave', models.CharField(blank=True, max_length=2, null=True)),
                ('id_clasificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.clasificacion')),
                ('id_estatus_observacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.estatusobservacion')),
            ],
            options={
                'db_table': 'observacion',
            },
        ),
        migrations.CreateModel(
            name='IntervencionObservacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_intervencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.intervencion')),
                ('id_observacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.observacion')),
            ],
            options={
                'db_table': 'intervencion_observacion',
            },
        ),
        migrations.CreateModel(
            name='ControlInternoObservacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_control_interno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.controlinterno')),
                ('id_observacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.observacion')),
            ],
            options={
                'db_table': 'control_interno_observacion',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaObservacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_auditoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.auditoria')),
                ('id_observacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.observacion')),
            ],
            options={
                'db_table': 'auditoria_observacion',
            },
        ),
        migrations.CreateModel(
            name='AccionesPreventivas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('denominacion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('id_observacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.observacion')),
            ],
            options={
                'db_table': 'acciones_preventivas',
            },
        ),
        migrations.CreateModel(
            name='AccionesCorrectivas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('denominacion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('id_observacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.observacion')),
            ],
            options={
                'db_table': 'acciones_correctivas',
            },
        ),
        migrations.AddField(
            model_name='actividadfiscalizacion',
            name='id_oic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.oic'),
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sexo', models.CharField(blank=True, max_length=30, null=True)),
                ('nombramiento', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('apellido', models.CharField(blank=True, max_length=200, null=True)),
                ('id_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.cargo')),
                ('id_oic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.oic')),
            ],
            options={
                'db_table': 'persona',
            },
        ),
    ]
