# Generated by Django 5.0.4 on 2024-06-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OICSec', '0002_sectorrevision_controlinterno_id_sector_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectorrevision',
            name='clave',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tiporevision',
            name='clave',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
