# Generated by Django 5.0.4 on 2024-06-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OICSec', '0003_alter_sectorrevision_clave_alter_tiporevision_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectorrevision',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
