# Generated by Django 5.0.4 on 2024-06-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OICSec', '0005_rename_sectorrevision_programarevision_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlinterno',
            old_name='rubro',
            new_name='area',
        ),
        migrations.RemoveField(
            model_name='controlinterno',
            name='unidad',
        ),
        migrations.AddField(
            model_name='controlinterno',
            name='denominacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='controlinterno',
            name='objetivo',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
