# Generated by Django 5.0.4 on 2024-06-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OICSec', '0007_alter_programarevision_clave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiporevision',
            name='clave',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tiporevision',
            name='tipo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
