# Generated by Django 5.0.4 on 2024-07-05 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OICSec', '0013_remove_cedula_id_tipo_cedula'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoCedula',
        ),
    ]
