# Generated by Django 5.0.4 on 2024-07-05 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OICSec', '0014_delete_tipocedula'),
    ]

    operations = [
        migrations.CreateModel(
            name='CedulaAuditoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_auditoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.auditoria')),
                ('id_cedula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.cedula')),
            ],
            options={
                'db_table': 'cedula_auditoria',
            },
        ),
        migrations.CreateModel(
            name='CedulaControlInterno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_cedula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.cedula')),
                ('id_control_interno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.controlinterno')),
            ],
            options={
                'db_table': 'cedula_control_interno',
            },
        ),
        migrations.CreateModel(
            name='CedulaIntervencion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_cedula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.cedula')),
                ('id_intervencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.intervencion')),
            ],
            options={
                'db_table': 'cedula_intervencion',
            },
        ),
    ]
