# Generated by Django 5.0.4 on 2024-07-08 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OICSec', '0016_cedula_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cedula',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='cedula',
            name='id_actividad_fiscalizacion',
        ),
        migrations.AddField(
            model_name='auditoria',
            name='id_cedula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.cedula'),
        ),
        migrations.AddField(
            model_name='controlinterno',
            name='id_cedula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.cedula'),
        ),
        migrations.AddField(
            model_name='intervencion',
            name='id_cedula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.cedula'),
        ),
    ]
