# Generated by Django 5.0.4 on 2024-07-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OICSec', '0017_remove_cedula_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='archivos/'),
        ),
    ]
