# Generated by Django 5.0.4 on 2024-07-12 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OICSec', '0019_alter_archivo_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cedulacontrolinterno',
            name='id_cedula',
        ),
        migrations.RemoveField(
            model_name='cedulacontrolinterno',
            name='id_control_interno',
        ),
        migrations.RemoveField(
            model_name='cedulaintervencion',
            name='id_cedula',
        ),
        migrations.RemoveField(
            model_name='cedulaintervencion',
            name='id_intervencion',
        ),
        migrations.DeleteModel(
            name='CedulaAuditoria',
        ),
        migrations.DeleteModel(
            name='CedulaControlInterno',
        ),
        migrations.DeleteModel(
            name='CedulaIntervencion',
        ),
    ]
