# Generated by Django 5.0.4 on 2024-07-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OICSec', '0021_persona_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(0, 'Inactivo'), (1, 'Activo')], null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=30, null=True),
        ),
    ]
