# Generated by Django 5.0.4 on 2024-07-16 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OICSec', '0023_alter_persona_estado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
