# Generated by Django 5.0.4 on 2024-07-16 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OICSec', '0024_delete_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('honorifico', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('apellido', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='TipoCargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'tipo_cargo',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')])),
                ('id_oic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.oic')),
                ('id_persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.persona')),
            ],
            options={
                'db_table': 'personal',
            },
        ),
        migrations.CreateModel(
            name='CargoPersonal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('id_personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.personal')),
                ('id_tipo_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.tipocargo')),
            ],
            options={
                'db_table': 'cargo_personal',
            },
        ),
    ]
