# Generated by Django 5.0.4 on 2024-07-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OICSec', '0025_persona_tipocargo_personal_cargopersonal'),
    ]

    operations = [
        migrations.AddField(
            model_name='minuta',
            name='tipo_concepto',
            field=models.IntegerField(blank=True, choices=[(1, 'Auditoria'), (2, 'Intervención'), (3, 'Control Interno')], null=True),
        ),
    ]
