# Generated by Django 5.0.4 on 2024-07-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OICSec', '0026_minuta_tipo_concepto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minuta',
            name='tipo_concepto',
        ),
        migrations.AddField(
            model_name='conceptominuta',
            name='tipo_concepto',
            field=models.IntegerField(blank=True, choices=[(1, 'Auditoria'), (2, 'Intervención'), (3, 'Control Interno')], null=True),
        ),
    ]
