# Generated by Django 5.0.4 on 2024-07-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OICSec', '0027_remove_minuta_tipo_concepto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='minuta',
            name='mes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
