# Generated by Django 5.0.4 on 2024-07-23 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OICSec', '0028_minuta_mes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinutaPersonal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_personal', models.IntegerField(blank=True, choices=[(1, 'Director Coordinación'), (2, 'JUD Coordinación'), (3, 'Titular OIC'), (4, 'Personal OIC')], null=True)),
                ('id_minuta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.minuta')),
                ('id_personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.personal')),
            ],
            options={
                'db_table': 'minuta_personal',
            },
        ),
    ]
