# Generated by Django 5.0.4 on 2024-07-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OICSec', '0029_minutapersonal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minuta',
            name='fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
