# Generated by Django 5.0.4 on 2024-07-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OICSec', '0030_alter_minuta_fin_alter_minuta_inicio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.AlterField(
            model_name='conceptominuta',
            name='tipo_concepto',
            field=models.IntegerField(blank=True, choices=[(1, 'Auditoria'), (2, 'Intervención'), (3, 'Control')], null=True),
        ),
    ]
