# Generated by Django 5.0.4 on 2024-08-15 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OICSec', '0031_delete_cargo_alter_conceptominuta_tipo_concepto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervencion',
            name='id_actividad_fiscalizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.actividadfiscalizacion'),
        ),
    ]
