# Generated by Django 5.0.4 on 2024-10-09 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OICSec', '0033_direccion_oic_id_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CedulaPersonal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_personal', models.IntegerField(blank=True, choices=[(1, 'Director Coordinación'), (2, 'Titular OIC')], null=True)),
                ('id_cedula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.cedula')),
                ('id_personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.personal')),
            ],
            options={
                'db_table': 'cedula_personal',
            },
        ),
    ]
