# Generated by Django 5.0.4 on 2024-10-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OICSec', '0034_cedulapersonal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minuta',
            name='id_tipo_minuta',
        ),
        migrations.AddField(
            model_name='cedula',
            name='realizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TipoMinuta',
        ),
    ]
