# Generated by Django 5.0.4 on 2024-10-11 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OICSec', '0035_remove_minuta_id_tipo_minuta_cedula_realizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(0, 'Inactivo'), (1, 'Activo')], null=True),
        ),
        migrations.CreateModel(
            name='AuditoriaArchivos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField(blank=True, choices=[(0, 'PAA'), (1, 'Incorporación'), (2, 'Cancelación'), (3, 'Modificación')], null=True)),
                ('id_archivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.archivo')),
                ('id_auditoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.auditoria')),
            ],
        ),
        migrations.CreateModel(
            name='ControlArchivos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField(blank=True, choices=[(0, 'PACI'), (1, 'Incorporación'), (2, 'Cancelación'), (3, 'Modificación')], null=True)),
                ('id_archivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.archivo')),
                ('id_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.controlinterno')),
            ],
        ),
        migrations.CreateModel(
            name='IntervencionArchivos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField(blank=True, choices=[(0, 'PINT'), (1, 'Incorporación'), (2, 'Cancelación'), (3, 'Modificación')], null=True)),
                ('id_archivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.archivo')),
                ('id_intervencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OICSec.intervencion')),
            ],
        ),
    ]
