# Generated by Django 5.0.4 on 2024-10-15 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OICSec', '0036_auditoria_estado_auditoriaarchivos_controlarchivos_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='auditoriaarchivos',
            table='auditoria_archivos',
        ),
        migrations.AlterModelTable(
            name='controlarchivos',
            table='control_archivos',
        ),
        migrations.AlterModelTable(
            name='intervencionarchivos',
            table='intervencion_archivos',
        ),
    ]
