# Generated by Django 5.0.4 on 2024-10-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OICSec', '0037_alter_auditoriaarchivos_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(0, 'Cancelada'), (1, 'Activa')], null=True),
        ),
    ]
